# Generated by Django 3.2.6 on 2021-09-30 11:03

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Sectors',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='construction', max_length=100, unique=True)),
                ('image', models.ImageField(upload_to=base.models.services_upload_path)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='house', max_length=100, unique=True)),
                ('feature', models.ImageField(upload_to=base.models.project_directory_path)),
                ('company', models.CharField(default='Cadeaux', max_length=100)),
                ('description', models.TextField()),
                ('value', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.sectors')),
                ('services', models.ManyToManyField(to='base.Services')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.types')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='projectGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=base.models.project_gallery)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.projects')),
            ],
            options={
                'verbose_name_plural': 'Gallery',
            },
        ),
    ]
