# Generated by Django 3.2.6 on 2022-01-09 08:09

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20211031_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to=base.models.team_upload_path)),
                ('names', models.CharField(max_length=200, unique=True)),
                ('position', models.CharField(max_length=200)),
                ('bio', models.TextField()),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Team',
            },
        ),
    ]
