# Generated by Django 3.2.6 on 2021-09-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Staff', 'Staff'), ('Admin', 'Admin'), ('Manager', 'Manager')], default='Staff', max_length=15),
        ),
    ]
