# Generated by Django 3.2.6 on 2021-09-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Staff', 'Staff'), ('Manager', 'Manager'), ('Admin', 'Admin')], default='Staff', max_length=15),
        ),
    ]
