# Generated by Django 3.2.6 on 2021-10-01 10:39

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(upload_to=account.models.profile_upload_path),
        ),
    ]
