# Generated by Django 3.2.6 on 2021-10-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Staff', 'Staff'), ('Admin', 'Admin')], default='Staff', max_length=15),
        ),
    ]
