# Generated by Django 3.2.6 on 2021-11-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinfo',
            name='password',
            field=models.CharField(default='hello', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Staff', 'Staff')], default='Staff', max_length=15),
        ),
    ]
