# Generated by Django 3.2.6 on 2022-01-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Staff', 'Staff'), ('Admin', 'Admin')], default='Staff', max_length=15),
        ),
    ]
