# Generated by Django 3.2.6 on 2022-01-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='display',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(default='...'),
        ),
    ]
